---
- name: Install Azure CLI
  hosts: all
  become: yes
  
  tasks:
  - name: Add Microsoft GPG key
    ansible.builtin.apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Add Azure CLI repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_facts.lsb.codename }} main"
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Install Azure CLI
    apt:
      name: azure-cli
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"