---
- name: Install Podman
  hosts: all
  become: yes
  
  tasks:
    - name: Ensure system packages are updated
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
    
    - name: Install Podman
      apt:
        name: 
        - podman
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Allow podman user to run services without being logged in
      command: loginctl enable-linger 1000