name: Deploy App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
  
  build:
    needs: [test]
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v4

  dev:
    needs: [build]
    if: github.ref_name == 'main'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

  prd:
    needs: [dev]
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    environment:
      name: prd

    steps:
    - uses: actions/checkout@v4