name: Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
  
  build:
    needs: [test]
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v4

  dev:
    needs: [build]
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

  prod:
    needs: [dev]
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    environment:
      name: prd

    steps:
    - uses: actions/checkout@v4