name: Deploy IaC

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      planOnly:
        required: true
        default: 'true'
      destroy:
        required: true
        default: 'false'

env:
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  lint:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Lint
      shell: bash
      run: |
        cd infra/terraform
        FMT=$(terraform fmt -recursive -check || true)
        
        if [ -n "$FMT" ]; then
          echo "Error: Please reformat Terraform files before pushing your changes!"
          exit 1
        fi

  dev:
    needs: [lint]
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '!['
        tokenSuffix: ']'
        files: '["**/*.tf", "**/*.tfvars"]'
      env:
        AKS_DNS_PREFIX: ${{ secrets.AKS_DNS_PREFIX }}
        ENTRAID_ADMIN_GROUP_ID: ${{ secrets.ENTRAID_ADMIN_GROUP_ID }}
        NAME_PREFIX: ${{ secrets.NAME_PREFIX }}
        PDZ_DOMAIN: ${{ secrets.PDZ_DOMAIN }}
        RG_NAME: ${{ secrets.RG_NAME }}
        SHARED_RG: ${{ secrets.SHARED_RG }}
        SHARED_STORAGE_ACCOUNT: ${{ secrets.SHARED_STORAGE_ACCOUNT }}
        TFSTATE_CONTAINER: ${{ secrets.TFSTATE_CONTAINER }}

    - name: Terraform Init
      shell: bash
      run: |
        cd infra/terraform
        
        terraform init

    - name: Terraform Plan
      shell: bash
      run: |
        cd infra/terraform
        
        cp DEV/terraform.tfvars ./

        terraform plan -out plan

    - name: Terraform Apply
      if: github.event.inputs.planOnly == 'false' && github.event.inputs.destroy == 'false'
      shell: bash
      run: |
        cd infra/terraform
        
        terraform plan -out plan.out

    - name: Terraform Destroy
      if: github.event.inputs.planOnly != 'true' && github.event.inputs.destroy == 'true'
      shell: bash
      run: |
        cd infra/terraform
        
        terraform destroy -auto-approve

  prd:
    needs: [dev]
    if: github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    environment:
      name: prd

    steps:
    - uses: actions/checkout@v4